name: Build and Release macOS Binary

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: brew install cmake

      - name: Install Raylib
        run: brew install raylib

      - name: Prepare build directories
        run: |
          mkdir -p build/dist/include
          mkdir -p build/dist/lib

      - name: Copy headers
        run: |
          cp src/*.h build/dist/include/ || true
          cp src/*.hpp build/dist/include/ || true

      - name: Configure with CMake
        working-directory: build
        run: cmake ..

      - name: Build with make
        working-directory: build
        run: make

      - name: Copy output to dist
        run: cp build/libnova.a build/dist/lib/

      - name: Create tarball
        working-directory: build
        run: tar -czvf dist-mac.tar.gz dist

      - name: Get latest release info
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput('upload_url', release.data.upload_url);
            core.setOutput('release_id', release.data.id);

      - name: Upload dist-mac.tar.gz to latest release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: build/dist-mac.tar.gz
          asset_name: dist-mac.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
